import "./globals.css";
import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";

import QueryProvider from "@/components/providers/QueryProvider";
import NextUiProvider from "@/components/providers/NextUIProvider";
import Navigation from "@/components/Navigation";

const sourceSans = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={sourceSans.className}>
        <QueryProvider>
          <NextUiProvider>
            <main className="flex h-screen w-full">
              <Navigation />
              {children}
            </main>
          </NextUiProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
